### ISSUE TITLE
uncaught exception in ExtInt interrupt handler line 1 AttributeError:

### ISSUE THREAD

**Issue by vahithosan** [peterhinch/micropython-samples#11]
Hi. Thanks to shearing encoder_timed.py. 

I want  use for measuring velocity  rotary encoder but can't.

`
>>> import encoder_timed
>>> e=encoder_timed.EncoderTimed('A1','A2',0,0)
>>> e.position
0
`

when using rotary encoder;

`
>>> uncaught exception in ExtInt interrupt handler line 1
AttributeError: 
uncaught exception in ExtInt interrupt handler line 2
AttributeError: 
`

added lines 

`
import micropython
`
`
micropython.alloc_emergency_exception_buf(100)`
`

`
>>> uncaught exception in ExtInt interrupt handler line 1
Traceback (most recent call last):
  File "encoder_timed.py", line 28, in x_callback
AttributeError: 'str' object has no attribute 'value'
uncaught exception in ExtInt interrupt handler line 2
Traceback (most recent call last):
  File "encoder_timed.py", line 34, in y_callback
AttributeError: 'str' object has no attribute 'value'

`

**Comment by peterhinch** [comment]
I think you are passing strings as **pin_x** and **pin_y** constructor arguments. They should be **Pin** instances (and those pins should be configured as inputs).
